apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ include "cpnr-local.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cpnr-local.name" . }}
    helm.sh/chart: {{ include "cpnr-local.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "cpnr-local.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cpnr-local.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cpnr-local.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      nodeName: {{ .Values.workerNode }}
      hostNetwork: true
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: [ "/usr/sbin/init" ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: webui
            containerPort: {{ .Values.service.webui.targetPort }}
            protocol: TCP
        env:
          - name: CNR_REGIONAL_IP
            {{- if .Values.cnrRegip }}
            value: {{ .Values.cnrRegip }}
            {{- else }}
            value: "10.195.73.172"
            {{- end }}
          - name: CNR_REGIONAL_CCM_PORT
            {{- if .Values.cnrccmPort }}
            value: "{{ .Values.cnrccmPort }}"
            {{- else }}
            value: "1244"
            {{- end }}
          - name: CNR_SERVICE
            {{- if .Values.cnrSvc }}
            value: {{ .Values.cnrSvc }}
            {{- else }}
            value: "dns"
            {{- end }}
          - name: CNR_LOCAL_CCM_PORT
            {{- if .Values.cnrlocalccmPort }}
            value: "{{ .Values.cnrlocalccmPort }}"
            {{- else }}
            value: "1234"
            {{- end }}
          - name: CNR_DNS_PORT
            {{- if .Values.cnrDnsport }}
            value: "{{ .Values.cnrDnsport }}"
            {{- else }}
            value: "53"
            {{- end }}
          - name: CNR_HTTPS_PORT
            {{- if .Values.cnrHttpsport }}
            value: "{{ .Values.cnrHttpsport }}"
            {{- else }}
            value: "53"
            {{- end }}
        lifecycle:
          postStart:
            exec:
              command: 
                - "sh"
                - "-c"
                - >
                  /scripts/cnr_init_local.sh -N {{ .Values.cnrUser }} -P {{ .Values.cnrPassword }}
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        volumeMounts:
          - mountPath: /scripts
            name: cnr-init
          {{- if (.Values.persistenceStorage.enabled) }}
          - name: {{ template "cpnr-local.fullname" . }}-data
            mountPath: /var/nwreg2/local
          {{- end }}
      volumes:
      - name: cnr-init
        configMap:
          name: {{ include "cpnr-local.fullname" . }}
          defaultMode: 0744
      {{- if (not (.Values.persistenceStorage.enabled)) }}
      - name: {{ template "cpnr-local.fullname" . }}-data
        emptyDir: {}
      {{ end }}
  {{- if (.Values.persistenceStorage.enabled) }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "cpnr-local.fullname" . }}-data
      spec:
        {{- if .Values.persistenceStorage.dataVolumeSource }}
        dataSource:
            name: {{ .Values.persistenceStorage.dataVolumeSource }}
            kind: VolumeSnapshot
            apiGroup: snapshot.storage.k8s.io
        {{- end }}
        accessModes:
          - {{ .Values.persistenceStorage.dataAccessMode | quote }}
        {{- if .Values.persistenceStorage.dataStorageClass }}
        {{- if (eq "-" .Values.persistenceStorage.dataStorageClass) }}
        storageClassName: default
        {{- else }}
        storageClassName: {{ .Values.persistenceStorage.dataStorageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistenceStorage.dataSize }}
  {{ end }}