# Default values for single-vm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: kubevirt
  name: cirros-registry-disk-demo
  tag: latest

service:
  type: NodePort
  port: 22

resources:
  requests:
    memory: 512Mi
