apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpnr-regional.fullname" . }} 
data:
  cnr_init_regional.sh: |-
{{ .Files.Get "configurations/cnr_init_regional.sh" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpnr-regional.fullname" . }}-lic
data:
  pnr.lic: |-
{{ .Files.Get "configurations/pnr.lic" | indent 4}}