apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpnr-regional.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cpnr-regional.name" . }}
    helm.sh/chart: {{ include "cpnr-regional.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webui.internalPort }}
      targetPort: {{ .Values.service.webui.targetPort }}
      protocol: TCP
      name: webui
  selector:
    app.kubernetes.io/name: {{ include "cpnr-regional.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}