apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cpnr-regional.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cpnr-regional.name" . }}
    helm.sh/chart: {{ include "cpnr-regional.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "cpnr-regional.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app.kubernetes.io/name: {{ include "cpnr-regional.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cpnr-regional.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      nodeName: {{ .Values.workerNode }}
      hostNetwork: true
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/usr/sbin/init"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: webui
            containerPort: {{ .Values.service.webui.targetPort }}
            protocol: TCP
        env:
          - name: CNR_LICENSE_FILE
            {{- if .Values.cnrLic }}
            value: {{ .Values.cnrLic }}
            {{- else }}
            value: "/license/pnr.lic"
            {{- end }}
          - name: CNR_REGIONAL_CCM_PORT
            {{- if .Values.cnrccmPort }}
            value: "{{ .Values.cnrccmPort }}"
            {{- else }}
            value: "1244"
            {{- end }}
        lifecycle:
          postStart:
            exec:
              command: 
                - "sh"
                - "-c"
                - >
                  /scripts/cnr_init_regional.sh -N {{ .Values.cnrUser }} -P {{ .Values.cnrPassword }}
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        volumeMounts:
          - mountPath: /scripts
            name: cnr-init-scripts
          - mountPath: /license
            name: cnr-lic
          {{- if (.Values.persistenceStorage.enabled) }}
          - name: {{ template "cpnr-regional.fullname" . }}-data
            mountPath: /var/nwreg2/regional
          {{- end }}
      volumes:
      - name: cnr-init-scripts
        configMap:
          name: {{ include "cpnr-regional.fullname" . }} 
          defaultMode: 0744
      - name: cnr-lic
        configMap:
          name: {{ include "cpnr-regional.fullname" . }}-lic
      {{- if (not (.Values.persistenceStorage.enabled)) }}
      - name: {{ template "cpnr-regional.fullname" . }}-data
        emptyDir: {}
      {{ end }}
  {{- if (.Values.persistenceStorage.enabled) }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "cpnr-regional.fullname" . }}-data
      spec:
        {{- if .Values.persistenceStorage.dataVolumeSource }}
        dataSource:
            name: {{ .Values.persistenceStorage.dataVolumeSource }}
            kind: VolumeSnapshot
            apiGroup: snapshot.storage.k8s.io
        {{- end }}
        accessModes:
          - {{ .Values.persistenceStorage.dataAccessMode | quote }}
        {{- if .Values.persistenceStorage.dataStorageClass }}
        {{- if (eq "-" .Values.persistenceStorage.dataStorageClass) }}
        storageClassName: default
        {{- else }}
        storageClassName: {{ .Values.persistenceStorage.dataStorageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistenceStorage.dataSize }}
  {{ end }}